AWSTemplateFormatVersion: '2010-09-09'
Description: Role to allow cross account access

Resources:
  CrossAccountRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cross-account-access-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: "arn:aws:iam::000000000000:user/AccountBUser" # LocalStack uses fake account
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                Resource: "*"

