pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
        AWS_ACCESS_KEY_ID = 'test'
        AWS_SCRET_ACCESS_KEY = 'test'
        AWS_DEFAULT_REGION = 'us-east-1'
        AWS_ENDPOINT = 'http://host.docker.internal:4566'
    }

    stages {
        stage('Deploy Account A Role') {
            steps {
                sh '''
                    echo "PWD is $PWD"
                    echo "AWS_PROFILE is $AWS_PROFILE"
                     ls -al

                    aws --endpoint-url=${AWS_ENDPOINT} cloudformation create-stack \
                        --stack-name account-a-role \
                        --template-body file://cloudformation/accountA-role.yaml  || \  

                    (aws --endpoint-url=${AWS_ENDPOINT} cloudformation update-stack \
                        --stack-name account-a-role \
                        --template-body file://cloudformation/accountA-role.yaml \
                        --capabilities CAPABILITY_NAMED_IAM || true)
                '''
            }
        }

        stage('Deploy Account B User') {
            steps {
                sh '''
                    aws --endpoint-url=${AWS_ENDPOINT} cloudformation create-stack \
                        --stack-name account-b-user \
                        --template-body file://cloudformation/accountB-user.yaml || \

                    (aws --endpoint-url=${AWS_ENDPOINT} cloudformation update-stack \
                        --stack-name account-b-user \
                        --template-body file://cloudformation/accountB-user.yaml \
                        --capabilities CAPABILITY_NAMED_IAM || true)
                '''
            }
        }

        stage('Deploy S3 Bucket') {
            steps {
                sh '''
                    aws --endpoint-url=${AWS_ENDPOINT} cloudformation create-stack \
                        --stack-name cross-account-bucket \
                        --template-body file://cloudformation/s3-bucket.yaml || \

                    (aws --endpoint-url=${AWS_ENDPOINT} cloudformation update-stack \
                        --stack-name cross-account-bucket \
                        --template-body file://cloudformation/s3-bucket.yaml \
                        --capabilities CAPABILITY_NAMED_IAM || true)
                '''
            }
        }
    }
}